// <auto-generated />
using System;
using KaiCoinMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KaiCoinMVC.Data.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20190321151003_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KaiCoinMVC.Models.Account", b =>
                {
                    b.Property<decimal>("AccountNumber");

                    b.Property<string>("Address");

                    b.Property<decimal?>("Balance");

                    b.Property<string>("City");

                    b.Property<string>("DOB");

                    b.Property<string>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNo");

                    b.Property<string>("State");

                    b.Property<decimal?>("ZipCode");

                    b.HasKey("AccountNumber");

                    b.ToTable("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
